Repository InfinyTech3D/Tearing, pull requests merged in 2024-02, with the labels that each got.

#22 [src] Use average stress per vertex to compute tearing candidates
  src/Tearing/TearingAlgorithms.h
  src/Tearing/TearingAlgorithms.inl
  src/Tearing/TearingEngine.h
  src/Tearing/TearingEngine.inl
Labels: pr: fix

#23 Sofa Tearing Plugin Documentation
  TearingPluginDocumentation.docx
  TearingPluginDocumentation.pdf
Labels: documentation

#26 [TearingEngine] Move computation of the new fracture segment out from draw method
  src/Tearing/TearingEngine.h
  src/Tearing/TearingEngine.inl
Labels: pr: clean

#29 [TearingEngine] Fix handleEvent logic if other event happened and clean draw method
  src/Tearing/TearingEngine.inl
Labels: pr: clean, pr: fix

#30 [TearingEngine] Clean and factorize some code in the computeVertex stress methods
  src/Tearing/TearingEngine.h
  src/Tearing/TearingEngine.inl
Labels: pr: clean, pr: fix
